name: Maven CI/CD

on:
  push:
    branches: [ Development ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del repositorio de Git
        uses: actions/checkout@v2

      - name: Configurar JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Probar el proyecto con Maven
        run: mvn -B test

      - name: Construir el proyecto con Maven
        run: mvn -B package

      - name: Get Version from POM.xml
        uses: entimaniac/read-pom-version-action@1.0.0
        id: getVersion

      - name: Copiar generado .war to staging  
        run: mkdir staging && cp target/*.war staging

      - name: Upload generated .war to Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: mvn-hello-world-${{ steps.getVersion.outputs.version }}.zip
          path: staging   